import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// import { Providers } from "./provider";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";
import ScrollToTop from "@/components/scroll";
import Cursor from "@/components/cursor";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "My Portfolio",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico", // file in /public
  },
};

export default function RootLayout({children}: Readonly<{children: React.ReactNode}>) {
  return (
    <html lang="en" className="scroll-smooth selection:bg-green-500 selection:text-white" suppressHydrationWarning>
      <body
      className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
    {/* <Providers> */}
      <Navbar/>
        {children}
        <Footer/>
        <ScrollToTop />
        <Cursor />


    {/* </Providers> */}
    </body>
    </html>
  );
}